export const VIEW_ORDER='VIEW_ORDER';
export const ADD_PRODUCT="ADD_PRODUCT";
export const THEME_ORDER="THEME_ORDER";
export const GET_COUNTRY="GET_COUNTRY";
export const GET_CURRENCY="GET_CURRENCY";
export const EDIT_ORDER="EDIT_ORDER";
export const PRODUCTS_VIEW='PRODUCTS_VIEW';
export const BRANDS_LIST='BRANDS_LIST'
export const GET_GROUP='GET_GROUP';
export const DATA_TO_STORE='DATA_TO_STORE';
export const PRODUCT_ITEM='PRODUCT_ITEM';
export const GET_INITIAL_CATEGORY="GET_INITIAL_CATEGORY";
export const VIEW_CATEGORY='VIEW_CATEGORY';
export const GET_PARTICULAR_CATEGORY="GET_PARTICULAR_CATEGORY";
export const GET_SUB_CATEGORY="GET_SUB_CATEGORY";
export const ON_SUBMIT="ON_SUBMIT";
export const ADD_BRAND='ADD_BRAND';
export const DISABLE_BRAND='DISABLE_BRAND';
export const DELETE_BRAND='DELETE_BRAND';
export const ENABLE_BRAND='ENABLE_BRANDS';
export const BRAND_DETAIL='BRAND_DETAIL';
export const UPDATE_BRAND_DETAILS='UPDATE_BRAND_DETAILS'
export const ADD_CUSTOMER='ADD_CUSTOMER';
export const GET_CUSTOMER='GET_CUSTOMER';
export const CREATE_PRODUCT='CREATE_PRODUCT';
export const GET_FILTER_PRODUCTS="GET_FILTER_PRODUCTS";
export const GET_STORES="GET_STORES";
export const CHANGE_STATUS='CHANGE_STATUS';
export const BRAND_PRODUCT='BRAND_PRODUCT';
export const GET_BLOG ='GET_BLOG';
export const PRODUCT_DATA ='PRODUCT_DATA';
export const PRODUCT_VARIANT ='PRODUCT_VARIANT';
export const POST_CREATE_PRODUCT='POST_CREATE_PRODUCT';
export const GET_PAGE_DETAIL='GET_PAGE_DETAIL';
export const GET_ACTIVE_PAGE_DETAIL='GET_ACTIVE_PAGE_DETAIL';
export const UPDATE_PRODUCT='UPDATE_PRODUCT';
export const UPDATE_VARIANT='UPDATE_VARIANT';
export const MOCK_PRODUCTS_VIEW ='MOCK_PRODUCTS_VIEW';
export const UPDATE_PRODUCT_ID='UPDATE_PRODUCT_ID';
export const SEARCH='SEARCH';
export const ENABLE_CATEGORY = 'ENABLE_CATEGORY';
export const CHANGE_STATUS_CATEGORY = 'CHANGE_STATUS_CATEGORY';
export const SEARCH_KEYWORD='SEARCH_KEYWORD'
export const SET_BREADCRUMB = 'SET_BREADCRUMB';




                    