export  const URN = 'http://localhost:4000';
// export const URL='https://ivf-inventory.herokuapp.com/api'
export const URL='http://192.168.1.104:3001/api';
export const BRANDURL='http://192.168.1.113:3000/api/brands';
export const VIEW_ORDER='VIEW_ORDER';
export const ADD_PRODUCT="ADD_PRODUCT";
export const THEME_ORDER="THEME_ORDER";
export const GET_COUNTRY="GET_COUNTRY";
export const GET_CURRENCY="GET_CURRENCY";
export const EDIT_ORDER="EDIT_ORDER";
export const PRODUCTS_VIEW='PRODUCTS_VIEW';
export const BRANDS_LIST='BRANDS_LIST'
export const GET_GROUP='GET_GROUP';
export const DATA_TO_STORE='DATA_TO_STORE';
export const PRODUCT_ITEM='PRODUCT_ITEM';
export const GET_INITIAL_CATEGORY="GET_INITIAL_CATEGORY";
export const GET_PARTICULAR_CATEGORY="GET_PARTICULAR_CATEGORY";
export const GET_SUB_CATEGORY="GET_SUB_CATEGORY";
export const ON_SUBMIT="ON_SUBMIT";
export const ADD_BRAND='ADD_BRAND';
export const DISABLE_BRAND='DISABLE_BRAND';
export const DELETE_BRAND='DELETE_BRAND';
export const ENABLE_BRAND='ENABLE_BRANDS';
export const BRAND_DETAIL='BRAND_DETAIL';
export const UPDATE_BRAND_DETAILS='UPDATE_BRAND_DETAILS'
export const GET_CITY='GET_CITY';
export const ADD_CUSTOMER='ADD_CUSTOMER';
export const GET_CUSTOMER='GET_CUSTOMER';
export const CHANGE_STATUS='CHANGE_STATUS'

                    